config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'homes#top'
  get '/about' => 'homes#about'
  get '/ranking' => 'presents#ranking'
  get 'search' => 'searches#search'
  # 新規登録ミス後にリロードするとエラーになるためルートパスに繋ぐ。
  get '/users' => 'homes#top'

  resources :users, only: [:show, :edit, :update] do
    member do
      get 'favorites'
      resource :relationships, only: [:create, :destroy]
      get 'follow' => 'relationships#follow'
    end
  end
  resources :presents do
    resources :comments, only: [:create, :destroy]
    member do
      patch :switch_return_status
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :friends, except: [:new]
  resources :events, except: [:show] do
    patch :switch_ready_status, on: :member
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  has_many :presents, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :kana_name, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :memo, length: { maximum: 300 }

  # 相手との関係性
  enum relation: {
    friends: 0,
    steady: 1,
    spouse: 2,
    dad_and_mom: 3,
    children: 4,
    siblings: 5,
    grandparents: 6,
    rekative: 7,
    superior: 8,
    colleague: 9,
    junior: 10,
    customer: 11,
    coworker: 12,
    others: 13,
  }

  enum gender: { male: 0, female: 1 }
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, except: [:index, :create]

  def index
    @friend = Friend.new
    # カナ降順順に並び替え
    @friends = current_user.friends.order(kana_name: "asc")
  end

  def create
    @friend = Friend.new(friend_params)
    @friend.user_id = current_user.id
    if @friend.save
      redirect_to friends_path, notice: "新しいフレンドが登録されました"
    else
      @friends = current_user.friends.order(kana_name: "asc")
      render :index
    end
  end

  def show
    @presents = @friend.presents
    @events = @friend.events
  end

  def edit
  end

  def update
    if @friend.update(friend_params)
      redirect_to friends_path
    else
      render :edit
    end
  end

  def destroy
    @friend.destroy
    redirect_to friends_path, notice: "フレンドを削除しました"
  end

  private

  def friend_params
    params.require(:friend).permit(:name, :kana_name, :relation, :gender, :memo)
  end

  def set_friend
  end

  def ensure_current_user
    @friend = Friend.find(params[:id])
    unless @friend.user_id == current_user.id
      redirect_to user_path(current_user), notice: "登録したご本人以外はアクセスできません。"
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with model: friend, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "名前" %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "山田太郎", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :kana_name, "フリガナ（空白なし）" %><br />
    <%= f.text_field :kana_name, autocomplete: "name", placeholder: "ヤマダタロウ", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :relation, "相手との関係" %><br />
    <%= f.select :relation, Friend.relations_i18n.keys.map {|k| [I18n.t("enums.friend.relation.#{k}"), k]}, { prompt: "選択してください" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :gender, "性別" %><br />
    <%= f.radio_button :gender, :male %>
    <%= f.label :gender, "男性" %>
    <%= f.radio_button :gender, :female %>
    <%= f.label :gender, "女性" %>
  </div>

  <div class="form-group">
    <%= f.label :memo, "一言メモ" %><br />
    <%= f.text_area :memo, placeholder: "贈り物の参考になる情報を記載しておこう", rows: "3", class: "form-control" %>
  </div>

  <div class="friend-form__btn">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="inner">
  <div class="form-wide">
    <h1 class="title">Editing Friend</h1>
    <p class="sub-title">フレンド情報編集</p>
    <%= render "layouts/errors", obj: @friend %>
    <%= render "form", friend: @friend %>
  </div>
</div>

app/views/friends/index.html.erb
<div class="inner">

  <div class="friend-index">
    <h1 class="title">Friends</h1>
    <p class="sub-title">フレンド一覧</p>
    <a id="new-btn"><i class="fas fa-user-plus"> フレンド登録</i></a>
    <%= render "layouts/errors", obj: @friend %>
    <% unless @friends.exists? %>
      <p>登録されたフレンドはいません。</p>
    <% else %>
      <div class="scroll">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>名前</th>
              <th>性別</th>
              <th>関係性</th>
              <th>メモ</th>
              <th>編集</th>
              <th>削除</th>
            </tr>
          </thead>
          <% @friends.each do |friend| %>
            <tbody>
                <tr>
                  <td data-link="<%= friend_path(friend) %>"><%= friend.name %></td>
                  <td data-link="<%= friend_path(friend) %>"><%= friend.gender_i18n %></td>
                  <td data-link="<%= friend_path(friend) %>"><%= friend.relation_i18n %></td>
                  <td data-link="<%= friend_path(friend) %>"><%= friend.memo %></td>
                  <td>
                    <%= link_to edit_friend_path(friend), class: "btn btn-primary" do %>
                      <p class="fas fa-edit"></p>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to friend_path(friend), method: :delete, data: { confirm: "フレンドに関するイベントや投稿も削除されます。\n本当に削除しますか？" }, class: "btn btn-secondary" do %>
                      <p class="far fa-trash-alt"></p>
                    <% end %>
                  </td>
                </tr>
            </tbody>
          </div>
        <% end %>
      </table>
    <% end %>
  </div>
  <div id="friend-new" class="off">
    <div class="form-inner">
    <h1 class="title">New Friend</h1>
    <p class="sub-title">フレンド新規登録</p>
    <%= render "form", friend: @friend %>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="inner">
    <h1 class="title">Your Friend</h1>
    <p class="sub-title">フレンド情報</p>
  <div class="friend-detail row justify-content-center">
    <div class="friend-table col-lg-3">
      <table class="table table-bordered">
        <thead>
          <tr><th colspan="2"><%= @friend.name %>さん</th></tr>
        </thead>
        <tbody>
          <tr>
            <th><i class="fas fa-venus-mars"></i></th>
            <td><%= @friend.gender_i18n %></td>
          </tr>
          <tr>
            <th><i class="fas fa-user-friends"></i></th>
            <td><%= @friend.relation_i18n %></td>
          </tr>
          <tr>
            <th><i class="fas fa-pen-fancy"></i></th>
            <td><%= @friend.memo %></td>
          </tr>
        </tbody>
      </table>
      <div class="friend-table__btn">
        <%= link_to edit_friend_path(@friend), class: "btn btn-primary" do %>
          <p class="fas fa-edit"></p>
        <% end %>
        <%= link_to friend_path(@friend), method: :delete, data: { confirm: "フレンドに関するイベントや投稿も削除されます。\n本当に削除しますか？" }, class: "btn btn-secondary" do %>
          <p class="far fa-trash-alt"></p>
        <% end %>
      </div>
    </div>


    <div class="friend-events col-lg-8">
      <h3 class="friend-events__title">Friend's Events</h3>
      <% unless @events.present? %>
        <p>フレンドに関するイベントはありません。</p>
      <% else %>
        <div class="scroll">
          <table class="table">
            <thead>
              <tr>
                <td>準備状況</td>
                <td>記念日</td>
                <td>シーン</td>
                <td>備忘録</td>
                <td>編集</td>
                <td>削除</td>
              </tr>
            </thead>
            <tbody>
              <% @events.each do |event| %>
                <tr>
                  <td>
                    <%= link_to event.ready_status_i18n, switch_ready_status_event_path(event), method: :patch, class: "switch__#{event.ready_status}" %>
                  </td>
                  <td><%= event.date %></td>
                  <td><%= event.scene_status_i18n %></td>
                  <td><%= event.memo %></td>
                  <td>
                    <%= link_to edit_event_path(event), class: "btn btn-primary" do %>
                        <p class="fas fa-edit"></p>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to event_path(event), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-secondary" do %>
                      <p class="far fa-trash-alt"></p>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
  <div class="friend-logs">
    <h1 class="title">Friend's Gift Logs</h1>
    <p class="sub-title">フレンドとの贈り物ログ</p>
    <div class="post-wrap">
      <%= render 'presents/index', presents: @presents %>
    </div>
  </div>

</div>