config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'homes#top'
  get '/about' => 'homes#about'
  get '/ranking' => 'presents#ranking'
  get 'search' => 'searches#search'
  # 新規登録ミス後にリロードするとエラーになるためルートパスに繋ぐ。
  get '/users' => 'homes#top'

  resources :users, only: [:show, :edit, :update] do
    member do
      get 'favorites'
      resource :relationships, only: [:create, :destroy]
      get 'follow' => 'relationships#follow'
    end
  end
  resources :presents do
    resources :comments, only: [:create, :destroy]
    member do
      patch :switch_return_status
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :friends, except: [:new]
  resources :events, except: [:show] do
    patch :switch_ready_status, on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :presents, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 会員がフォローしている人
  has_many :followings, through: :active_relationships, source: :followed
  # 会員をフォローしている人
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
  validates :birthday, presence: true
  validates :gender, presence: true
  validates :introduce, length: { maximum: 300 }

  enum gender: { male: 0, female: 1 }

  attachment :image

  # フォローしているか確認(フォローボタンで活用)
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_sign_up_params, only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birthday, :gender])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    ranking_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    ranking_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :ensure_current_user, only: [:edit, :update]

  def show
    @presents = @user.presents.order(created_at: 'desc').page(params[:page])
    @to_presents = @user.presents.where(gift_status: "0").order(created_at: 'desc').page(params[:page])
    @from_presents = @user.presents.where(gift_status: "1").order(created_at: 'desc').page(params[:page])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを更新しました。"
    else
      render :edit
    end
  end

  def favorites
    favorites = @user.favorites.order(created_at: :desc).pluck(:present_id)
    presents = Present.find(favorites)
    @presents = Kaminari.paginate_array(presents).page(params[:page])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_current_user
    unless @user == current_user
      redirect_to user_path(current_user), notice: "ユーザーご本人のみアクセスできます。"
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduce, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_post.html.erb
<% if presents.exists? %>
  <% presents.each do |gift| %>
    <div class="user-post row">

      <div class="post-left col-md-4">
        <p><%= gift.created_at.strftime('%Y/%m/%d') %></p>
        <%= link_to present_path(gift) do %>
          <p><%= attachment_image_tag gift, :item_image, format:'jpg', fallback:'no-image.jpg' %></p>
        <% end %>
      </div>

      <div class="post-center col-md-6">
        <p>品名：<%= gift.item %></p>
        <p>贈り物シーン：<%= gift.scene_status_i18n %><p>
        <% if gift.user_id == current_user.id %>
          <p>相手：<%= gift.friend.name %>さん (<%= gift.friend.relation_i18n %>)</p>
        <% else %>
          <p>相手：<%= gift.friend.relation_i18n %> (<%= gift.age_i18n %>)</p>
        <% end %>
        <p>一言メモ：<%= gift.memo.truncate(50, separator: /\s/)  %></p>
        <p><%= link_to gift.comments.count, present_path(gift, anchor: "comments-area"), class: "far fa-comment-dots" %></p>
        <div id="favorite_<%= gift.id %>">
          <%= render "favorites/favorite", present: gift %>
        </div>
      </div>

      <% if gift.user_id == current_user.id %>
        <div class="post-right col-md-2">
          <%= link_to gift.return_status_i18n, switch_return_status_present_path(gift.id), method: :patch, class: "switch__#{gift.return_status}" %>
        </div>
      <% end %>

    </div>
  <% end %>
<% else %>
  <p>該当する贈り物はありません。</p>
<% end %>

app/views/users/edit.html.erb
<div class="inner">
  <h1 class="title">Editing Profile</h1>
  <p class="sub-title">会員情報編集</p>
  <%= render "layouts/errors", obj: @user %>
  <%= form_with model:@user, local: true do |f| %>
    <div class="user-edit row justify-content-center">
      <div class="user-edit__left col-sm-5">
        <div class="form-group">
          <%= attachment_image_tag @user, :image, format:"jpg", fallback: "noimage-user.jpg", id: "preview" %>
        </div>
        <div class="form-group">
          <%= f.label :image_id, "プロフィール画像" %><br />
          <%= f.attachment_field :image, class: "form-control-file" %>
        </div>
      </div>
      <div class="user-edit__right col-sm-5">
        <div class="form-group">
          <%= f.label :name, "ニックネーム" %><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "name", size: "30", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :introduce, "自己紹介" %><br />
          <%= f.text_area :introduce, cols: "30", rows: "5", class:"form-control" %>
        </div>
        <div class="user-edit__btn">
          <%= f.submit "更新", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/favorites.html.erb
<div class="inner">
  <h1 class="title">Favotites</h1>
  <p class="sub-title">お気に入りにした贈り物</p>
  <div class="favorites-wrap">
    <div class="post-wrap">
      <%= render "presents/index", presents: @presents %>
    </div>
    <%= paginate @presents %>
  </div>
</div>

app/views/users/show.html.erb
<div class="inner">
  <h1 class="title">Profile</h1>
  <p class="sub-title">会員ページ</p>
  <div class="row justify-content-center">
    <div class="user-info col-sm-5">
      <p><%= attachment_image_tag @user, :image, format:'jpg', fallback:'noimage-user.jpg' %></p>
        <div class="user-info__item">
          <h5>Follower</h5>
          <p id="followers_count_<%= @user.id %>"><%= link_to @user.followers.count, follow_user_path(@user, anchor: "tab1" ) %></p>
        </div>
        <div class="user-info__item">
          <h5>Follow</h5>
          <p id="following_count_<%= @user.id %>"><%= link_to @user.followings.count, follow_user_path(@user, anchor: "tab2") %></p>
        </div>
        <div class="user-info__item">
          <h5>お気に入り</h5>
          <p><%= link_to @user.favorites.count, favorites_user_path(@user) %></p>
        </div>
    </div>
    <div class="profile col-sm-6">
      <p class="profile__title">ニックネーム</p>
      <p><%= @user.name %></p>
      <p class="profile__title">自己紹介</p>
      <p><%= @user.introduce %></p>
      <div class="profile__button">
        <% if @user.id == current_user.id %>
          <%= link_to "編集", edit_user_path(current_user), class: "btn btn-primary" %>
        <% else %>
          <div id="follow_btn_<%= @user.id %>">
            <%= render 'relationships/follow_btn', user: @user %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="user-tab">
    <h1 class="title">Gift Log</h1>
    <p class="sub-title">贈り物記録</p>
    <ul id="tab-menu">
      <li id="tab1"><a href="#panel1">全ての贈り物</a></li>
      <li id="tab2"><a href="#panel2">贈ったもの</a></li>
      <li id="tab3"><a href="#panel3">いただきもの</a></li>
    </ul>

    <div id="tab-panels">
      <div id="panel1" class="panel">
        <%= render "user_post", presents: @presents %>
        <%= paginate @presents %>
      </div>
      <div id="panel2" class="panel">
        <%= render "user_post", presents: @to_presents %>
        <%= paginate @to_presents %>
      </div>
      <div id="panel3" class="panel">
        <%= render "user_post", presents: @from_presents %>
        <%= paginate @from_presents %>
      </div>
    </div>
  </div>
</div>