config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'homes#top'
  get '/about' => 'homes#about'
  get '/ranking' => 'presents#ranking'
  get 'search' => 'searches#search'
  # 新規登録ミス後にリロードするとエラーになるためルートパスに繋ぐ。
  get '/users' => 'homes#top'

  resources :users, only: [:show, :edit, :update] do
    member do
      get 'favorites'
      resource :relationships, only: [:create, :destroy]
      get 'follow' => 'relationships#follow'
    end
  end
  resources :presents do
    resources :comments, only: [:create, :destroy]
    member do
      patch :switch_return_status
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :friends, except: [:new]
  resources :events, except: [:show] do
    patch :switch_ready_status, on: :member
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :friend

  validates :date, presence: true
  validates :ready_status, presence: true
  validates :scene_status, presence: true

  # 贈り物の準備ステータス
  enum ready_status: { preparation: 0, ready: 1 }
  # 贈り物の理由
  enum scene_status: {
    birthday: 0,
    anniversary: 1,
    summer_gift: 2,
    year_end_giht: 3,
    otosidama: 4,
    wedding: 5,
    newborn: 6,
    admission: 7,
    graduation: 8,
    incense: 9,
    others: 10,
  }

  # 贈り物準備ステータスボタンをスイッチ
  def switch_ready_status!
    if preparation?
      ready!
    else
      preparation!
    end
  end

  # simple_calendar用メソッド
  def start_time
    date
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, except: [:index, :new, :create]

  def index
    # 今後のイベントのみ取得
    @feature_events = current_user.events.where(date: Date.today..Float::INFINITY).order(:date)
    @events = current_user.events.order(date: 'desc').page(params[:page])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  def switch_ready_status
    @event.switch_ready_status!
    redirect_to request.referer
  end

  private

  def event_params
    params.require(:event).permit(:friend_id, :date, :memo, :scene_status, :ready_status)
  end

  def ensure_current_user
    @event = Event.find(params[:id])
    unless @event.user_id == current_user.id
      redirect_to user_path(current_user), notice: "登録したご本人以外はアクセスできません。"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with model: event, local: true do |f| %>
  <div class="form-group">
    <%= f.label :friend_id, "贈り物をする相手" %><br />
    <%= f.collection_select :friend_id, current_user.friends.all, :id, :name, {prompt: "選択してください"}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date, "記念日" %><br />
    <%= f. date_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :scene_status, "贈り物のシーン" %><br />
    <%= f.select :scene_status, Event.scene_statuses_i18n.keys.map {|k| [I18n.t("enums.event.scene_status.#{k}"), k]}, { prompt: "選択してください" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :ready_status, "贈り物準備状況" %><br />
    <%= f.radio_button :ready_status, :preparation %>
    <%= f.label :ready_status, "準備中" %>
    <%= f.radio_button :ready_status, :ready %>
    <%= f.label :ready_status, "準備完了" %>
  </div>

  <div class="form-group">
    <%= f.label :memo, "備忘録" %><br />
    <%= f.text_area :memo, placeholder: "贈り物の参考になる情報を記載しよう", class: "form-control" %>
  </div>

  <div class="event__action">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/_list.html.erb
<% unless events.exists? %>
  <p>予定されている記念日はありません。</p>
<% else %>
  <div class="scroll">
    <table class="table table-hover">
        <thead>
          <tr>
            <td>準備状況</td>
            <td>記念日</td>
            <td>贈る相手</td>
            <td>関係</td>
            <td>性別</td>
            <td>備忘録</td>
            <td>編集</td>
            <td>削除</td>
          </tr>
        </thead>
        <tbody>
          <% events.each do |event| %>
            <tr>
              <td>
                <%= link_to event.ready_status_i18n, switch_ready_status_event_path(event), method: :patch, class: "switch__#{event.ready_status}" %>
              </td>
              <td data-link="<%= friend_path(event.friend) %>"><%= event.date %></td>
              <td data-link="<%= friend_path(event.friend) %>"><%= event.friend.name %></td>
              <td data-link="<%= friend_path(event.friend) %>"><%= event.friend.relation_i18n %></td>
              <td data-link="<%= friend_path(event.friend) %>"><%= event.friend.gender_i18n %></td>
              <td data-link="<%= friend_path(event.friend) %>"><%= event.memo %></td>
              <td>
                <%= link_to edit_event_path(event), class: "btn btn-primary" do %>
                    <p class="fas fa-edit"></p>
                <% end %>
              </td>
              <td>
                <%= link_to event_path(event), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-secondary" do %>
                  <p class="far fa-trash-alt"></p>
                <% end %>
              </td>
            </tr>
          <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="form-wide">
  <h1 class="title">Editing Event</h1>
  <p class="sub-title">記念日の編集</p>
  <div class="event-form">
    <%= render "layouts/errors", obj: @event %>
    <%= render "form", event: @event %>
  </div>
</div>

app/views/events/index.html.erb
<div class="events-wrap">
  <h1 class="title">Feature Events</h1>
  <p class="sub-title">今後の記念日</p>
  <%= link_to "新規イベント作成", new_event_path, class: "btn", id: "new-btn" %>
  <%= render "list", events: @feature_events %>
  <h1 class="title">All Events</h1>
  <p class="sub-title">記念日一覧</p>
  <%= render "list", events: @events %>
  <%= paginate @events %>
</div>

app/views/events/new.html.erb
<div class="form-wide">
  <h1 class="title">New Event</h1>
  <p class="sub-title">新規記念日作成</p>
  <div class="event-form">
    <%= render "layouts/errors", obj: @event %>
    <%= render "form", event: @event %>
  </div>
</div>