config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'homes#top'
  get '/about' => 'homes#about'
  get '/ranking' => 'presents#ranking'
  get 'search' => 'searches#search'
  # 新規登録ミス後にリロードするとエラーになるためルートパスに繋ぐ。
  get '/users' => 'homes#top'

  resources :users, only: [:show, :edit, :update] do
    member do
      get 'favorites'
      resource :relationships, only: [:create, :destroy]
      get 'follow' => 'relationships#follow'
    end
  end
  resources :presents do
    resources :comments, only: [:create, :destroy]
    member do
      patch :switch_return_status
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :friends, except: [:new]
  resources :events, except: [:show] do
    patch :switch_ready_status, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :present

  validates :comment, presence: true, length: { maximum: 300 }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :friend

  validates :date, presence: true
  validates :ready_status, presence: true
  validates :scene_status, presence: true

  # 贈り物の準備ステータス
  enum ready_status: { preparation: 0, ready: 1 }
  # 贈り物の理由
  enum scene_status: {
    birthday: 0,
    anniversary: 1,
    summer_gift: 2,
    year_end_giht: 3,
    otosidama: 4,
    wedding: 5,
    newborn: 6,
    admission: 7,
    graduation: 8,
    incense: 9,
    others: 10,
  }

  # 贈り物準備ステータスボタンをスイッチ
  def switch_ready_status!
    if preparation?
      ready!
    else
      preparation!
    end
  end

  # simple_calendar用メソッド
  def start_time
    date
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :present

  validates_uniqueness_of :present_id, scope: :user_id
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  has_many :presents, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :kana_name, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :memo, length: { maximum: 300 }

  # 相手との関係性
  enum relation: {
    friends: 0,
    steady: 1,
    spouse: 2,
    dad_and_mom: 3,
    children: 4,
    siblings: 5,
    grandparents: 6,
    rekative: 7,
    superior: 8,
    colleague: 9,
    junior: 10,
    customer: 11,
    coworker: 12,
    others: 13,
  }

  enum gender: { male: 0, female: 1 }
end

app/models/present.rb
class Present < ApplicationRecord
  belongs_to :user
  belongs_to :friend
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :age, presence: true
  validates :item, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }
  validates :memo, length: { maximum: 300 }

  attachment :item_image

  # 年代
  enum age: {
    baby: 0,
    under_teens: 1,
    teens: 2,
    twenties: 3,
    thirties: 4,
    fourties: 5,
    fifties: 6,
    sixties: 7,
    seventies_and_over: 8,
  }
  # 送受ステータス
  enum gift_status: { give: 0, receive: 1 }
  # 贈り物の理由
  enum scene_status: {
    birthday: 0,
    anniversary: 1,
    summer_gift: 2,
    year_end_giht: 3,
    otosidama: 4,
    wedding: 5,
    newborn: 6,
    admission: 7,
    graduation: 8,
    incense: 9,
    others: 10,
  }
  # お返しの状態
  enum return_status: { unnecessary: 0, preparation: 1, done: 2 }

  # お返しステータスボタンを変更するメソッド
  def switch_return_status!
    if preparation?
      done!
    elsif done?
      preparation!
    else
      unnecessary!
    end
  end

  # お気に入りされているか確認
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # タイトルと内容とタグで検索。
  # タグテーブルはcontrolerでinculdes済
  scope :search, -> (content){
    where("(item LIKE ?) OR (memo LIKE ?) OR (name LIKE ?)", '%' + content + '%', '%' + content + '%', '%' + content + '%')
  }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord

  belongs_to :present

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :presents, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 会員がフォローしている人
  has_many :followings, through: :active_relationships, source: :followed
  # 会員をフォローしている人
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
  validates :birthday, presence: true
  validates :gender, presence: true
  validates :introduce, length: { maximum: 300 }

  enum gender: { male: 0, female: 1 }

  attachment :image

  # フォローしているか確認(フォローボタンで活用)
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :ensure_current_user, only: [:edit, :update]

  def show
    @presents = @user.presents.order(created_at: 'desc').page(params[:page])
    @to_presents = @user.presents.where(gift_status: "0").order(created_at: 'desc').page(params[:page])
    @from_presents = @user.presents.where(gift_status: "1").order(created_at: 'desc').page(params[:page])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを更新しました。"
    else
      render :edit
    end
  end

  def favorites
    favorites = @user.favorites.order(created_at: :desc).pluck(:present_id)
    presents = Present.find(favorites)
    @presents = Kaminari.paginate_array(presents).page(params[:page])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_current_user
    unless @user == current_user
      redirect_to user_path(current_user), notice: "ユーザーご本人のみアクセスできます。"
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduce, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2>※入力内容に誤りがあります。</h2>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; 2021 konomi1 </p>
</footer>

app/views/layouts/_pc-sidebar.html.erb
<div class="sidebar">
  <div class="sidebar__logo">
    <%= link_to root_path do %>
      <%= image_tag asset_path('logo.png'), alt: "PRESENTIST", class: "top-logo" %>
    <% end %>
  </div>

  <nav class="sidebar__nav">
    <ul class="sidebar__ul">
      <% if user_signed_in? %>
        <li><%= link_to "ホーム", ranking_path, class:"btn sidebar__btn" %></li>
        <li><%= link_to "マイページ", user_path(current_user.id), class:"btn sidebar__btn" %></li>
        <li><%= link_to "贈り物ログ", presents_path, class:"btn sidebar__btn" %></li>
        <li><%= link_to "記念日", events_path, class:"btn sidebar__btn" %></li>
        <li><%= link_to "フレンド", friends_path, class:"btn sidebar__btn" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn sidebar__btn" %></li>
      <% else %>
        <li><%= link_to "Top", root_path, class:"btn sidebar__btn" %></li>
        <li><%= link_to "About", about_path, class:"btn sidebar__btn" %></li>
        <li><%= link_to 'Ranking', ranking_path, class:"btn sidebar__btn" %></li>
        <li><%= link_to "Log in", new_user_session_path, class:"btn sidebar__btn" %></li>
        <li><%= link_to "Sign Up", new_user_registration_path, class:"btn sidebar__btn" %></li>
      <% end %>
    </ul>
  </nav>
  <% if user_signed_in? %>
    <p><%= link_to "ログ作成", new_present_path, class:"fas fa-gifts btn btn-link" %></p>
  <% end %>
</div>

app/views/layouts/_sp-header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light">
    <a class="navbar-brand" href="/">
      <%= image_tag asset_path('logo.png'), alt: "PRESENTIST", class: "top-logo" %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#dropdown" aria-controls="dropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="dropdown">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to " ホーム", ranking_path, class:"btn fas fa-home" %></li>
          <li><%= link_to " マイページ", user_path(current_user.id), class:"btn fas fa-user-cog"  %></li>
          <li><%= link_to " 贈り物ログ", presents_path, class:"btn fas fa-gift"  %></li>
          <li><%= link_to " 記念日", events_path, class:"btn fas fa-calendar-alt"  %></li>
          <li><%= link_to " フレンド", friends_path, class:"btn fas fa-users"  %></li>
          <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete, class:"btn fas fa-sign-out-alt"  %></li>
        <% else %>
          <li><%= link_to "Top", root_path, class:"btn sp__btn"  %></li>
          <li><%= link_to "About", about_path, class:"btn sp__btn"  %></li>
          <li><%= link_to 'Ranking', ranking_path, class:"btn sp__btn"  %></li>
          <li><%= link_to "Log in", new_user_session_path, class:"btn sp__btn"  %></li>
          <li><%= link_to "Sign Up", new_user_registration_path, class:"btn sp__btn"  %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <% if user_signed_in? %>
    <p><%= link_to "ログ作成", new_present_path, class:"fas fa-gifts btn btn-link" %></p>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Presentist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless controller.controller_name.in?(['registrations','sessions','homes']) %>
      <header class="sp-header">
        <%= render "layouts/sp-header" %>
      </header>

      <main class="container-fluid">

        <div class="row">
          <div class="pc-sidebar col-md-3 col-xl-2 px-0">
            <%= render "layouts/pc-sidebar" %>
          </div>

          <div class="contents col-sm-12 col-md-9 col-xl-10 px-0">
            <% unless controller.controller_name == 'presents' && controller.action_name == 'ranking' %>
              <p class="notice"><%= notice %></p>
              <div class="search-form">
                <%= render "searches/search_form" %>
              </div>
            <% end %>
            <%= yield %>
            <%= render "layouts/footer" %>
          </div>
        </div>
      </main>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>